### ISSUE TITLE
GenieBuilder.jl errors out on startup under MacOS Catalina

### ISSUE THREAD

**Issue by rswgnu** [GenieFramework/GenieBuilder.jl#20]
Using the latest stable Julia release as of today on MacOS 10.15.7 (Catalina), I followed the instructions to setup GenieBuilder, wrote the token file required and then got this error.  Maybe some other initialization is necessary that is not in the instructions.  (I didn't do any of the manual repl setup or add julia to my PATH yet).

julia> using Genie; Genie.loadapp()
┌ Error: 2022-07-30 18:29:49 Exception while generating log record in module GenieBuilder.ApplicationsController at /Users/bk/Dropbox/GitHub/julia/GenieBuilder.jl/app/resources/applications/ApplicationsController.jl:775
│   exception =
│    UndefRefError: access to undefined reference
│    Stacktrace:
│      [1] getproperty
│        @ ./Base.jl:42 [inlined]
│      [2] getindex
│        @ ./refvalue.jl:56 [inlined]
│      [3] macro expansion
│        @ ./logging.jl:360 [inlined]
│      [4] ready()
│        @ GenieBuilder.ApplicationsController ~/Dropbox/GitHub/julia/GenieBuilder.jl/app/resources/applications/ApplicationsController.jl:775
│      [5] ready
│        @ ~/Dropbox/GitHub/julia/GenieBuilder.jl/routes.jl:123 [inlined]
│      [6] main()
│        @ GenieBuilder ~/Dropbox/GitHub/julia/GenieBuilder.jl/routes.jl:129
│      [7] top-level scope
│        @ ~/Dropbox/GitHub/julia/GenieBuilder.jl/bootstrap.jl:5
│      [8] include(fname::String)
│        @ Base.MainInclude ./client.jl:451
│      [9] top-level scope
│        @ ~/.julia/packages/Genie/mMGS8/src/Genie.jl:101
│     [10] eval
│        @ ./boot.jl:373 [inlined]
│     [11] loadapp(path::String; autostart::Bool, dbadapter::Nothing)
│        @ Genie ~/.julia/packages/Genie/mMGS8/src/Genie.jl:100
│     [12] loadapp (repeats 2 times)
│        @ ~/.julia/packages/Genie/mMGS8/src/Genie.jl:96 [inlined]
│     [13] top-level scope
│        @ REPL[6]:1
│     [14] eval
│        @ ./boot.jl:373 [inlined]
│     [15] eval_user_input(ast::Any, backend::REPL.REPLBackend)
│        @ REPL /Applications/Julia-1.7.app/Contents/Resources/julia/share/julia/stdlib/v1.7/REPL/src/REPL.jl:150
│     [16] repl_backend_loop(backend::REPL.REPLBackend)
│        @ REPL /Applications/Julia-1.7.app/Contents/Resources/julia/share/julia/stdlib/v1.7/REPL/src/REPL.jl:246
│     [17] start_repl_backend(backend::REPL.REPLBackend, consumer::Any)
│        @ REPL /Applications/Julia-1.7.app/Contents/Resources/julia/share/julia/stdlib/v1.7/REPL/src/REPL.jl:231
│     [18] run_repl(repl::REPL.AbstractREPL, consumer::Any; backend_on_current_task::Bool)
│        @ REPL /Applications/Julia-1.7.app/Contents/Resources/julia/share/julia/stdlib/v1.7/REPL/src/REPL.jl:364
│     [19] run_repl(repl::REPL.AbstractREPL, consumer::Any)
│        @ REPL /Applications/Julia-1.7.app/Contents/Resources/julia/share/julia/stdlib/v1.7/REPL/src/REPL.jl:351
│     [20] (::Base.var"#936#938"{Bool, Bool, Bool})(REPL::Module)
│        @ Base ./client.jl:394
│     [21] #invokelatest#2
│        @ ./essentials.jl:716 [inlined]
│     [22] invokelatest
│        @ ./essentials.jl:714 [inlined]
│     [23] run_main_repl(interactive::Bool, quiet::Bool, banner::Bool, history_file::Bool, color_set::Bool)
│        @ Base ./client.jl:379
│     [24] exec_options(opts::Base.JLOptions)
│        @ Base ./client.jl:309
│     [25] _start()
│        @ Base ./client.jl:495
└ @ GenieBuilder.ApplicationsController ~/Dropbox/GitHub/julia/GenieBuilder.jl/app/resources/applications/ApplicationsController.jl:775
ERROR: LoadError: UndefRefError: access to undefined reference
Stacktrace:
  [1] getproperty
    @ ./Base.jl:42 [inlined]
  [2] getindex
    @ ./refvalue.jl:56 [inlined]
  [3] ready()
    @ GenieBuilder.ApplicationsController ~/Dropbox/GitHub/julia/GenieBuilder.jl/app/resources/applications/ApplicationsController.jl:778
  [4] ready
    @ ~/Dropbox/GitHub/julia/GenieBuilder.jl/routes.jl:123 [inlined]
  [5] main()
    @ GenieBuilder ~/Dropbox/GitHub/julia/GenieBuilder.jl/routes.jl:129
  [6] top-level scope
    @ ~/Dropbox/GitHub/julia/GenieBuilder.jl/bootstrap.jl:5
  [7] include(fname::String)
    @ Base.MainInclude ./client.jl:451
  [8] top-level scope
    @ ~/.julia/packages/Genie/mMGS8/src/Genie.jl:101
  [9] eval
    @ ./boot.jl:373 [inlined]
 [10] loadapp(path::String; autostart::Bool, dbadapter::Nothing)
    @ Genie ~/.julia/packages/Genie/mMGS8/src/Genie.jl:100
 [11] loadapp (repeats 2 times)
    @ ~/.julia/packages/Genie/mMGS8/src/Genie.jl:96 [inlined]
 [12] top-level scope
    @ REPL[6]:1
in expression starting at /Users/bk/Dropbox/GitHub/julia/GenieBuilder.jl/bootstrap.jl:5

**Comment by essenciary** [comment]
@rswgnu GenieBuilder is available as a plugin in the VSCode marketplace. The users don't need to are not expected to run things at the Julia REPL. Can you please detail what instructions you followed?

**Comment by rswgnu** [comment]
Hi:

I followed the instructions in the README.md file right here in this Github repo, but missed the first section and jumped right to the install section.  Thanks fir the clarification.

**Comment by essenciary** [comment]
Hehe, no worries, I just added the first section :) 

Works correctly now? Can we close this issue?

**Comment by rswgnu** [comment]
I haven't had a chance to reinstall it but you can close this issue as the install procedure is different now.
